export const getStreamData = () => {
  return [
    {
      id: 1,
      songName: "Blinding Lights",
      artist: "The Weeknd",
      dateStreamed: "2024-02-10",
      streamCount: 10500,
      userId: "U123",
    },
    {
      id: 2,
      songName: "Shape of You",
      artist: "Ed Sheeran",
      dateStreamed: "2024-02-09",
      streamCount: 9800,
      userId: "U456",
    },
    {
      id: 3,
      songName: "Anti-Hero",
      artist: "Taylor Swift",
      dateStreamed: "2024-02-08",
      streamCount: 8900,
      userId: "U789",
    },
    {
      id: 4,
      songName: "Levitating",
      artist: "Dua Lipa",
      dateStreamed: "2024-02-07",
      streamCount: 8700,
      userId: "U234",
    },
    {
      id: 5,
      songName: "Good 4 U",
      artist: "Olivia Rodrigo",
      dateStreamed: "2024-02-06",
      streamCount: 8600,
      userId: "U567",
    },
    {
      id: 6,
      songName: "Stay",
      artist: "The Kid LAROI & Justin Bieber",
      dateStreamed: "2024-02-05",
      streamCount: 8500,
      userId: "U890",
    },
    {
      id: 7,
      songName: "Save Your Tears",
      artist: "The Weeknd",
      dateStreamed: "2024-02-04",
      streamCount: 8300,
      userId: "U321",
    },
    {
      id: 8,
      songName: "Peaches",
      artist: "Justin Bieber",
      dateStreamed: "2024-02-03",
      streamCount: 8100,
      userId: "U654",
    },
    {
      id: 9,
      songName: "Happier Than Ever",
      artist: "Billie Eilish",
      dateStreamed: "2024-02-02",
      streamCount: 8000,
      userId: "U987",
    },
    {
      id: 10,
      songName: "Montero (Call Me By Your Name)",
      artist: "Lil Nas X",
      dateStreamed: "2024-02-01",
      streamCount: 7900,
      userId: "U111",
    },

    {
      id: 11,
      songName: "Industry Baby",
      artist: "Lil Nas X & Jack Harlow",
      dateStreamed: "2024-01-31",
      streamCount: 7700,
      userId: "U222",
    },
    {
      id: 12,
      songName: "drivers license",
      artist: "Olivia Rodrigo",
      dateStreamed: "2024-01-30",
      streamCount: 7500,
      userId: "U333",
    },
    {
      id: 13,
      songName: "Watermelon Sugar",
      artist: "Harry Styles",
      dateStreamed: "2024-01-29",
      streamCount: 7400,
      userId: "U444",
    },
    {
      id: 14,
      songName: "Dance Monkey",
      artist: "Tones and I",
      dateStreamed: "2024-01-28",
      streamCount: 7300,
      userId: "U555",
    },
    {
      id: 15,
      songName: "Memories",
      artist: "Maroon 5",
      dateStreamed: "2024-01-27",
      streamCount: 7200,
      userId: "U666",
    },
    {
      id: 16,
      songName: "Someone You Loved",
      artist: "Lewis Capaldi",
      dateStreamed: "2024-01-26",
      streamCount: 7100,
      userId: "U777",
    },
    {
      id: 17,
      songName: "Roses",
      artist: "SAINt JHN",
      dateStreamed: "2024-01-25",
      streamCount: 7000,
      userId: "U888",
    },
    {
      id: 18,
      songName: "Circles",
      artist: "Post Malone",
      dateStreamed: "2024-01-24",
      streamCount: 6900,
      userId: "U999",
    },
    {
      id: 19,
      songName: "Sunflower",
      artist: "Post Malone & Swae Lee",
      dateStreamed: "2024-01-23",
      streamCount: 6800,
      userId: "U101",
    },
    {
      id: 20,
      songName: "Senorita",
      artist: "Shawn Mendes & Camila Cabello",
      dateStreamed: "2024-01-22",
      streamCount: 6700,
      userId: "U202",
    },
    {
      id: 21,
      songName: "bad guy",
      artist: "Billie Eilish",
      dateStreamed: "2024-01-21",
      streamCount: 6600,
      userId: "U303",
    },
    {
      id: 22,
      songName: "Shallow",
      artist: "Lady Gaga & Bradley Cooper",
      dateStreamed: "2024-01-20",
      streamCount: 6500,
      userId: "U404",
    },
    {
      id: 23,
      songName: "Without Me",
      artist: "Halsey",
      dateStreamed: "2024-01-19",
      streamCount: 6400,
      userId: "U505",
    },
    {
      id: 24,
      songName: "Lucid Dreams",
      artist: "Juice WRLD",
      dateStreamed: "2024-01-18",
      streamCount: 6300,
      userId: "U606",
    },
    {
      id: 25,
      songName: "HUMBLE.",
      artist: "Kendrick Lamar",
      dateStreamed: "2024-01-17",
      streamCount: 6200,
      userId: "U707",
    },
    {
      id: 26,
      songName: "Rockstar",
      artist: "Post Malone & 21 Savage",
      dateStreamed: "2024-01-16",
      streamCount: 6100,
      userId: "U808",
    },
    {
      id: 27,
      songName: "7 rings",
      artist: "Ariana Grande",
      dateStreamed: "2024-01-15",
      streamCount: 6000,
      userId: "U909",
    },
    {
      id: 28,
      songName: "God's Plan",
      artist: "Drake",
      dateStreamed: "2024-01-14",
      streamCount: 5900,
      userId: "U010",
    },
    {
      id: 29,
      songName: "Sicko Mode",
      artist: "Travis Scott",
      dateStreamed: "2024-01-13",
      streamCount: 5800,
      userId: "U1110",
    },
    {
      id: 30,
      songName: "One Dance",
      artist: "Drake",
      dateStreamed: "2024-01-12",
      streamCount: 5700,
      userId: "U1211",
    },
  ];
};
